- hosts: relpulp
  become: true
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Install deps for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python

    - name: Gather facts
      setup:

    - name: Ensure vagrant in wheel group
      user: name=vagrant groups=wheel append=yes

    - name: Upgrade all packages
      dnf: name=* state=latest

  roles:
    - web
